export const SERVICE_ACCOUNT_CREDENTIAL_TYPE =
    process.env.SERVICE_ACCOUNT_CREDENTIAL_TYPE;
export const SERVICE_ACCOUNT_CREDENTIAL_PROJECT_ID =
    process.env.SERVICE_ACCOUNT_CREDENTIAL_PROJECT_ID;
export const SERVICE_ACCOUNT_CREDENTIAL_PRIVATE_KEY_ID =
    process.env.SERVICE_ACCOUNT_CREDENTIAL_PRIVATE_KEY_ID;
export const SERVICE_ACCOUNT_CREDENTIAL_PRIVATE_KEY =
    process.env.SERVICE_ACCOUNT_CREDENTIAL_PRIVATE_KEY;
export const SERVICE_ACCOUNT_CREDENTIAL_CLIENT_EMAIL =
    process.env.SERVICE_ACCOUNT_CREDENTIAL_CLIENT_EMAIL;
export const SERVICE_ACCOUNT_CREDENTIAL_CLIENT_ID =
    process.env.SERVICE_ACCOUNT_CREDENTIAL_CLIENT_ID;
export const SERVICE_ACCOUNT_CREDENTIAL_AUTH_URI =
    process.env.SERVICE_ACCOUNT_CREDENTIAL_AUTH_URI;
export const SERVICE_ACCOUNT_CREDENTIAL_TOKEN_URI =
    process.env.SERVICE_ACCOUNT_CREDENTIAL_TOKEN_URI;
export const SERVICE_ACCOUNT_CREDENTIAL_AUTH_PROVIDER_X509_CERT_URL =
    process.env.SERVICE_ACCOUNT_CREDENTIAL_AUTH_PROVIDER_X509_CERT_URL;
export const SERVICE_ACCOUNT_CREDENTIAL_CLIENT_X509_CERT_URL =
    process.env.SERVICE_ACCOUNT_CREDENTIAL_CLIENT_X509_CERT_URL;
export const SERVICE_ACCOUNT_CREDENTIAL_UNIVERSE_DOMAIN =
    process.env.SERVICE_ACCOUNT_CREDENTIAL_UNIVERSE_DOMAIN;

export const TELEGRAM_BOT_TOKEN = process.env.TELEGRAM_BOT_TOKEN;

export const CHANNEL_IDS = {
    KEI_LOK: process.env.TELEGRAM_CHANNEL_ID_KEI_LOK,
    ZE_YEUNG: process.env.TELEGRAM_CHANNEL_ID_ZE_YEUNG,
    LIANG_DING: process.env.TELEGRAM_CHANNEL_ID_LIANG_DING
};
export const PORT = process.env.PORT || 5500;
